server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: user-status-check
        uri: lb://demo-resource-server
        predicates[0]: Path=/users/api/welcome
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie