server:
  port: 8081


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservicedev
          jwk-set-uri: http://localhost:8080/realms/microservicedev/protocol/openid-connect/certs