server:
  port: 0 # Starts spring boot application on random port

eureka:
  client:
    enabled: false

spring:
  cloud:
    config:
      enabled: false
  application:
    name: demo-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservicedev
          jwk-set-uri: http://localhost:8080/realms/microservicedev/protocol/openid-connect/certs