server:
  port: 8084

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sumitmaji/spring-app-prop-repo
          searchPaths: demo-resource-server
          cloneOnStart: true
